config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 # delete 'books/:id' => 'books#destroy', as: 'destroy_books'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user
  validates :title, presence: true
  validates :body, presence: true,  length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :books, dependent: :destroy
    has_one_attached :profile_image
     validates :name, uniqueness: true, length: {in:2..20 }
     validates :introduction,  length: { maximum: 50}
     def get_profile_image(weight, height)
      unless profile_image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpg')
        profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
      profile_image.variant(resize_to_limit: [weight,height]).processed
     end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
   before_action :configure_permitted_parameters, if: :devise_controller?
   
  def after_sign_in_path_for(resource)
     user_path(current_user.id)
  end
  def after_sign_out_path_for(resource)
     root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  protected
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :correct_user, only: [:edit, :update]
  def create
     @book = Book.new(books_params)
    @book.user_id = current_user.id
    if@book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
    @user = current_user
    @books =Book.all
      render :index
    end
  end
  def index
    @user = current_user
    @books =Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.new
  end

  def edit
    @book =Book.find(params[:id])
   if @book.user == current_user
       render "edit"
   else
      redirect_to books_path
   end
   
  end
  def
   update
   @book = Book.find(params[:id])
  if @book.update(books_params)
    flash[:notice] = "You have updated book successfully."
   redirect_to book_path(@book.id) 
  else
    render :edit
  end
  end
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
     redirect_to books_path
  end

  private

  def books_params
    params.require(:book).permit(:body,:title)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
  def index
     @user = current_user
     @book = Book.new
     @books = Book.all
     @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
     @user = User.find(params[:id])
  if @user.id == current_user.id
            render "edit"
  else
            redirect_to user_path(current_user.id)
  end
  end
  def update
   @user = User.find(params[:id])
  if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
  else
     render :edit
  end
  end
  private

  def user_params
    params.require(:user).permit(:name,:profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/_user.html.erb
<h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
      <tbody>
        <tr></tr>
        <tr>
        <th>name <%= user.name %></th>
        </tr>
        <tr>
        <th>introduction <%= user.introduction %></th>
        </tr>
     </tbody>
    </table>
     <div class="row">
       <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
       <i class="fas fa-user-cog"></i>
       <% end %>
     </div>
  <h2>New book</h2>
  <%= form_with model: book do |f| %>
  <h6>Title</h6>
     <%= f.text_field :title %>
   <h6>Opinion</h6>
    <%= f.text_area :body %>
     <p><%= f.submit 'Create Book', class: "btn btn btn-success" %></p>
  <% end %>

app/views/books/edit.html.erb
  <% if @book.errors.any? %>
     <%= @book.errors.count %>errors prohibited this obj from being saved:
   <ul>
     <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
     <% end %>
   </ul>
     <% end %>
<div class="container">
 <div class="row">
   <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %>
      <h6>Title</h6>
         <%= f.text_field :title, size: "40x20" %>
       <h6>Opinion</h6>
        <%= f.text_area :body, size: "43" %>
       <p><%= f.submit 'Update Book',class: "btn btn-success" %></p>
        <%end%>
        <%= link_to "Show", book_path %>
        <%= "|" %>
        <%= link_to "Back", books_path %>
   </div>
 </div>
 </div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
   <div class="row">
      <div class="col-md-3">
     <%= render 'user', user: @user,book: @book %>
      </div>
     <% if @book.errors.any? %>
     <%= @book.errors.count %>errors prohibited this obj from being saved:
   <ul>
     <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
     <% end %>
   </ul>
     <% end %>
<div class="col-md-8 offset-md-1">
     <h2>Books</h2>
     <table class="table table-hover table-inverse">
       <thead>
        <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
        </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
       <tr>
          <td>
            <%= link_to user_path(book.user_id) do %>
            <%= image_tag book.user.get_profile_image(80,80) %>
            <% end %>
          </td>
         <td><%= link_to book.title, book_path(book.id) %></td>
         <td><%= book.body %></td>
         <% end %>
       </tr>
    </tbody>
    </table>
    </div>
    </div>
    </div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
   <div class="row">
      <div class="col-md-3">
        <%= render 'user', user: @user,book: @books %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <td><%= image_tag @book.user.get_profile_image(100,100) %>
              <br><%= link_to @book.user.name,user_path(@user.id) %>
            </td>
            <td><%= link_to @book.title,book_path(@user.id) %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book.id),class: "btn btn-sm btn-success edit_book_24279" %></td>
              <td><%= link_to "Destroy", book_path(@book.id),method: :delete, "data-confirm" => "本当に削除しますか？",class: "btn btn-sm btn-danger" %></td>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  

app/views/homes/about.html.erb
<div class="container">
   <div class="row">
     <h1 class="px-3 mx-auto">
        welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !
    </h1>
</div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
<h1>welcome to
<i class="fas fa-book"></i>
<strong>Bookers</strong>
 !! 
</h1>
<P>In
<i class="fas fa-book"></i>
<strong>Bookers,</strong>
</p>
 <p> you can share and exchange your opinions ,
  inpressions , and emotions</P>
<p>about various books!</p>
<div class="btn-wrapper col-10 mx-auto">
  <div class="row">
<%= link_to "Log in",user_session_path(@user),class: "btn btn-info btn-sm btn-block mb-3 sing_in" %>
</div>
<div class="row">
<%= link_to "Sign up", new_user_registration_path(@user),class: "btn btn-success btn-sm btn-block sign_up" %>
</div>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <span><%= link_to "Bookers", root_path,class: "navbar-brand" %></span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
       <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
         <i class="fas fa-home"></i>Home
         <% end %>
         
       </li>
       <li>
         <%= link_to users_path,class: 'nav-link text-light' do%>
         <i class="fas fa-users"></i>Users
         <% end %>
       </li>
       <li>
         <%= link_to books_path,class: 'nav-link text-light' do%>
        <i class="fas fa-book-open"></i>Books
        <% end %>
       </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
       <i class="fas fa-sign-out-alt"></i>Log out
       <% end %>
       
      </li>
    <% else %>
      <li>
        <%= link_to root_path,class: 'nav-link text-light' do %>
        <i class="fas fa-home"></i>Home
          <% end %>
      </li>
      <li>
       <%= link_to home_about_path,class: 'nav-link text-light' do %>
       <i class="fas fa-link"></i>About
       <% end %>
      </li>
      <li>
        <%= link_to  new_user_registration_path,class: 'nav-link text-light' do %>
        <i class="fas fa-user-plus"></i>Sign up
        <% end %>
      </li>
      <li>
        <%= link_to user_session_path,class: 'nav-link text-light' do %>
        <i class="fas fa-sign-in-alt"></i>Log in
        <% end %>
      </li>
      <% end %> 
    </ul>
    </div>
    </div>
    </nav>
    </header>
    <%= flash[:notice] %>
    <%= yield %>
    <footer>
      <div class="container mt-5">
      <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
        </div>
        </div>
        </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
     <% if @user.errors.any? %>
     <%= @user.errors.count %>error prohibited this obj from being saved:
   <ul>
     <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
     <% end %>
   </ul>
     <% end %>
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<%= form_with model: @user do |f| %>
<h6>Name</h6>
  <h6> <%= f.text_field :name, size: "40x20" %></h6>
   <h6>Image</h6>
  <%= f.file_field :profile_image, accept: "image/*" %>
  <h6>Introduction</h6>
    <%= f.text_area :introduction, size: "43" %>
     <p><%= f.submit 'Update User', class: "btn btn-secondary" %></p>
  <% end %>
  </div>
  </div>
  </div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
   <div class="row">
      <div class="col-md-3">
<%= render 'books/user', user: @user,book: @book %>
</div>
<div class="col-md-8 offset-md-1">
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>imag</th>
      <th>name</th>
       <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
          <% @users.each do |user| %>
   </tr>
      <td><%= image_tag user.get_profile_image(80,80) %></td>
      <td><%= user.name %></td>
      <td><%= link_to "Show", user_path(user.id) %></td>
          <% end %>
    </tr>
</tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
   <div class="row">
      <div class="col-md-3">
        <%= render 'books/user', user: @user,book: @book  %>
      </div>
     <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
       <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
        </tr>
        </thead>
        <tbody>
           <% @books.each do |book| %>
           <tr>
             <td>
             <%= link_to user_path(@user.id) do %>
             <%= image_tag book.user.get_profile_image(100,100) %>
             <% end %>
             </td>
             <td> <%= link_to book.title,book_path(book.id)%></td>
             <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
 </div>
  